### ISSUE TITLE
Measure Robot Pose Setpoints

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#13]
To design effective autonomous routines and useful teleop driver automations, we need to measure & record robot poses on the field.

**Positions**
- [x] Close shooting into Speaker
- [x] Far shooting into Speaker
- [x] Shooting into Amp
- [ ] Align with chains on stage to lift in endgage

**Impl. Details**

```java
public enum Position {

	AmpShootFar(new Pose2d()),

	AmpShootClose(new Pose2d());

	public final Pose2d pose;

    private Position(Pose2d pose) {
      this.pose = pose;
    }
}
```

**Comment by recursiveforte** [comment]
what is ColorScheme?

**Comment by henrikvtcodes** [comment]
Oops that is something that I forgot to change from the place that I copied and pasted that from
