### ISSUE TITLE
Flip Field Oriented Driving & Paths automatically based on FMS Alliance

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#14]
IIRC Pathplanner requires paths to be drawn on the blue side in order for them to be mirrored properly. As such, we should default to the robot being on the blue side when not connected to the FMS

**Comment by recursiveforte** [comment]
This has already been implemented (see `public static Pose2d flipPose(Pose2d pose)` in `Drive.java` + various checks of `DriverStation.getAlliance().get() == Alliance.Red`)
