### ISSUE TITLE
Tune Shooter

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#9]
**Required Prerequisite:** #7 
Tune shooter PID & feedforward controllers to ensure accurate shooting and position holding.  

*Flywheels*
- The flywheels should quickly recover to the set speed with minimal oscillating around the setpoint

_Pivot_
- The shooter pivoting mechanism should reliably drive to and hold setpoint
- It should not sag while the robot is on
- It should not wildly overcorrect when moved

**Comment by recursiveforte** [comment]
Also need to get data for `frc.robot.constants.ShooterConstants.ArticulationMap`.
